home/urls.py
from django.urls import path
from .views import HomeTemplateview, MenuTemplateview

urlpatterns = [
    path('', HomeTemplateview.as_view(), name='home'),
    path('menu/', MenuTemplateview.as_view(), name='menu'),
]

option/urls.py
from django.urls import path
from .views import OptionListView

urlpatterns = [
    path('', OptionListView.as_view(), name='option-list'),
] 

sanguchazo/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('option/', include('option.urls')),
] 

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

category/models.py
from pyexpat import model
from django.db import models


class Category(models.Model):
    name = models.CharField('Nombre', max_length=100)
    name_en = models.CharField('Name', max_length=100, blank=True, null=True)
    image = models.ImageField('Imagen', upload_to='category', blank=True, null=True)

    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"

    def __str__(self):
        return f'{self.name} - {self.name_en}'

home/models.py
from django.db import models

# Create your models here.

option/models.py
from django.db import models
from category.models import Category


class Option(models.Model):

    name = models.CharField('Nombre', max_length=100)
    name_en = models.CharField('Name', max_length=100, blank=True, null=True)
    description = models.TextField('Descripcion', blank=True, null=True)
    description_en = models.TextField('Description', blank=True, null=True)
    category = models.ForeignKey(Category, verbose_name='Categoria', on_delete=models.CASCADE)
    price = models.FloatField('Precio', default=0)
    recommended = models.BooleanField('Recomendado', default=False)
    
    class Meta:
        verbose_name = "Comida"
        verbose_name_plural = "Comidas"

    def __str__(self):
        return self.name

category/views.py
from django.shortcuts import render

# Create your views here.

home/views.py
from django.shortcuts import render
from django.views.generic import TemplateView

from category.models import Category
from option.models import Option


class HomeTemplateview(TemplateView):
    template_name = "home/home.html"
    

class MenuTemplateview(TemplateView):
    template_name = "home/menu.html"
    
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["recommended"] = Option.objects.filter(recommended=True)
        context["categories"] = Category.objects.all()
        return context
    

option/views.py
from django.shortcuts import render
from django.views.generic import ListView
from .models import Option
from category.models import Category

class OptionListView(ListView):
    model = Option
    template_name = "option/list.html"
    
    def get_context_data(self, **kwargs):
        category = self.request.GET.get('category', False)
        context = super().get_context_data(**kwargs)
        context["category"] = Category.objects.get(name=category)
        return context
    
    
    def get_queryset(self):
        qs = Option.objects.all()
        category = self.request.GET.get('category', False)
        
        if category:
            qs = Option.objects.filter(category__name=category)
        
        return qs
    
    
    
    

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta
      name="viewport"
      content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0"
    />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <title>Menu | El Sanguchazo</title>
    <link
      rel="stylesheet"
      href="{% static 'bootstrap/css/bootstrap.min.css' %}"
    />
    <link rel="stylesheet" href="{% static 'css/style.css' %}" />
  </head>
  <body>
    <p class="title">El Sanguchazo</p>

    <div class="container">{% block content %} {% endblock content %}</div>
  </body>
</html>

templates/home/category.html
<div class="row">
  {% for category in categories %}
  <div class="col-6 p-2">
    <a class="btn btn-success btn-md w-100" href="{% url 'option-list' %}?category={{category.name}}&lang={{request.GET.lang}}">
      
      {% if request.GET.lang == 'en' %}
        {{category.name_en}}
      {% else %}
        {{category.name}}
      {% endif %}

    </a>
  </div>
  {% endfor %}
</div>

templates/home/home.html
{% extends 'base.html' %}
    
{% block content %}

<div class='row'>
    <p class="text-white text-center mt-5">Selecciona un idioma - Select a language</p>
    <div class="col-xl-6 col-md-6 col-sm-12 col-xs-12">
        <a class='btn btn-xl btn-success w-100 mt-3' href="{% url 'menu' %}?lang=en">Ingles</a>
    </div>
    <div class="col-xl-6 col-md-6 col-sm-12 col-xs-12">
        <a class='btn btn-xl btn-success w-100 mt-4' href="{% url 'menu' %}?lang=es">Español</a>
    </div>
</div>

{% endblock content %}

templates/home/menu.html
{% extends 'base.html' %} {% block content %}

{% include 'home/category.html' %}
{% include 'home/recommended.html' %}
  
{% endblock content %}

templates/home/recommended.html
{% if recommended %}
  <p class="text-center text-white mb-4 mt-4">Recomendaciones - Recommendations</p>
  <div class="row">
    {% for option in recommended %}
      <div class="col-12 col-xl-3 col-md-6 col-sm-12 mb-3">
        <div class="card bg-dark text-white mb-3">
          <div class="card-body d-flex flex-column">
            <div class="d-flex">
              {% if request.GET.lang == 'en' %}
                {{option.name_en}}
              {% else %}
                {{option.name}}
              {% endif %}
              <h5 class="mt-auto ms-auto">${{option.price}}</h5>
            </div>
            {% if request.GET.lang == 'en' %}
              <p class="text-muted mt-auto mb-auto">{{option.description_en}}</p>
            {% else %}
              <p class="text-muted mt-auto mb-auto">{{option.description}}</p>
            {% endif %}
          </div>
        </div>
      </div>
    {% endfor %}
  </div>
{% endif %}

templates/option/list.html
{% extends 'base.html' %}

{% block content %}

<h3 class="text-light mb-3 mt-5 text-center">{{category.name|capfirst}}</h3>

{% if category.image %}
    <img class="card-img" src="{{category.image.url}}" />
{% endif %}

<div class="row">
    {% for option in option_list %}
        <div class="col-12 col-xl-3 col-md-6 col-sm-12 mb-3">
        <div class="card bg-dark text-white mb-3">
            {% if option.img %}
            <img class="card-img" src="{{option.img.url}}" />
            {% endif %}
            <div class="card-body d-flex flex-column">
            <div class="d-flex">
                {% if request.GET.lang == 'en' %}
                    {{option.name_en}}
                {% else %}
                    {{option.name}}
                {% endif %}
                <h5 class="mt-auto ms-auto">${{option.price}}</h5>
            </div>
                {% if request.GET.lang == 'en' %}
                    <p class="text-muted mt-auto mb-auto">{{option.description_en}}</p>
                {% else %}
                    <p class="text-muted mt-auto mb-auto">{{option.description}}</p>
                {% endif %}
            </div>
        </div>
        </div>
    {% empty %}
    <p class="text-light text-center mt-3">No hay nada para mostrar</p>
    <p class="text-light text-center mt-3 mb-5">There is nothing to show</p>
    {% endfor %} 
</div>

<div class="row mx-1">
    <a class="btn btn-secondary btn-md" href="{% url 'menu' %}?lang={{request.GET.lang}}">Volver Atras - Go Back</a>
</div>
{% endblock content %}